/**
 * AI-Powered Communication Composer
 * Generates marketing copy with A/B subject lines and integrated CTA
 */

import OpenAI from 'openai'
import { BusinessProfile } from '@/libs/chat-core/src/types'
import { CommunicationSettings } from './types'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
})

export interface ComposerResult {
  subjectLines: string[] // Exactly 3 subject line options
  body: string // Body text with integrated CTA
}

/**
 * Generates communication content (subject lines and body) using AI
 */
export async function generateCommunicationContent(
  prompt: string,
  profile: BusinessProfile,
  settings: CommunicationSettings
): Promise<ComposerResult> {
  try {
    const primaryCta = settings.primaryCta || 'Contact us for more information'
    
    const aiPrompt = `
You are an Expert Direct Response Marketer. Your job is to write persuasive, conversion-focused marketing copy.

**Business Context:**
- Business Name: ${profile.businessName}
- Industry: ${profile.industry}
- Location: ${JSON.stringify(profile.location)}
- Brand Voice: ${profile.brandVoice || 'professional'}
- Target Audience: ${profile.targetAudience || 'Local customers'}
- Services: ${JSON.stringify(profile.services || [])}

**User's Request:**
${prompt}

**Primary CTA (Call-to-Action):**
"${primaryCta}"

**Requirements:**
1. Generate exactly 3 distinct subject line options. Each must be:
   - Compelling and attention-grabbing
   - Relevant to the user's request
   - Different from the others (diverse approaches)
   - Appropriate length for email/SMS (50-70 characters recommended)

2. Generate a single body text that:
   - Addresses the user's request or topic
   - Is persuasive and conversion-focused
   - Naturally incorporates the CTA: "${primaryCta}" into the body
   - The CTA should feel like a natural part of the message, not tacked on
   - Match the brand voice: ${profile.brandVoice || 'professional'}
   - Be appropriate length for email/SMS (200-500 words recommended)

**Output Format:**
Return a JSON object with this exact structure:
{
  "subjectLines": [
    "First subject line option",
    "Second subject line option",
    "Third subject line option"
  ],
  "body": "Full body text with the CTA naturally integrated: ${primaryCta}"
}

Ensure the body text naturally includes the CTA "${primaryCta}" in a way that flows with the content.`

    const response = await openai.chat.completions.create({
      model: 'gpt-4-turbo-preview',
      messages: [
        {
          role: 'system',
          content: 'You are an Expert Direct Response Marketer who writes persuasive, conversion-focused marketing copy. Always return valid JSON that matches the exact structure provided.'
        },
        {
          role: 'user',
          content: aiPrompt
        }
      ],
      temperature: 0.8, // Higher temperature for creative subject lines
      max_tokens: 1500,
      response_format: { type: 'json_object' }
    })

    const content = response.choices[0]?.message?.content
    if (!content) {
      throw new Error('No content generated by AI')
    }

    // Parse the JSON response
    let parsedData: any
    try {
      parsedData = JSON.parse(content)
    } catch (parseError) {
      throw new Error('Failed to parse AI response as JSON')
    }

    // Extract subject lines and body
    const subjectLines = parsedData.subjectLines || []
    const body = parsedData.body || ''

    // Validate that we have exactly 3 subject lines
    if (!Array.isArray(subjectLines) || subjectLines.length !== 3) {
      throw new Error(`Expected 3 subject lines, got ${subjectLines.length}`)
    }

    // Validate that all subject lines are strings and non-empty
    const validSubjectLines = subjectLines
      .filter((line: any) => typeof line === 'string' && line.trim().length > 0)
      .map((line: string) => line.trim())
      .slice(0, 3)

    if (validSubjectLines.length < 3) {
      throw new Error(`Invalid subject lines: expected 3 valid strings`)
    }

    // Validate body
    if (!body || typeof body !== 'string' || body.trim().length === 0) {
      throw new Error('Invalid or missing body text')
    }

    return {
      subjectLines: validSubjectLines,
      body: body.trim()
    }
  } catch (error: any) {
    console.error('[Composer] Error generating communication content:', error)
    throw new Error(`Failed to generate communication content: ${error.message}`)
  }
}

