/**
 * Content Adapter for Social Media Platforms
 * Adapts content for Instagram and Twitter/X using AI
 */

import OpenAI from 'openai'
import { BusinessProfile } from '../../chat-core/src/types'
import { SocialPlatform } from './types'

// Lazy initialization to avoid build errors when API key is not set
let openai: OpenAI | null = null
function getOpenAI(): OpenAI {
  if (!openai) {
    const apiKey = process.env.OPENAI_API_KEY
    if (!apiKey) {
      throw new Error('OPENAI_API_KEY environment variable is not set')
    }
    openai = new OpenAI({ apiKey })
  }
  return openai
}

/**
 * Platform-specific character limits
 * V1.5: Added google_business limits (GBP posts are typically shorter, ~500 chars)
 */
export const PLATFORM_LIMITS: Record<SocialPlatform, { max: number; warning: number }> = {
  twitter: { max: 280, warning: 260 },
  linkedin: { max: 3000, warning: 2900 },
  facebook: { max: 63206, warning: 63000 },
  instagram: { max: 2200, warning: 2100 },
  google_business: { max: 500, warning: 450 } // V1.5: GBP standard posts
}

/**
 * Adapts content for a specific platform using AI
 * 
 * @param baseContent - The original content to adapt
 * @param platform - Target platform ('instagram' | 'twitter')
 * @param profile - Business profile for context
 * @returns Adapted content for the platform
 */
export async function adaptContentForPlatform(
  baseContent: string,
  platform: 'instagram' | 'twitter',
  profile: BusinessProfile
): Promise<string> {
  const platformGuidelines = getPlatformGuidelines(platform)
  
  const prompt = `You are an Expert Social Media Strategist. Your task is to adapt content for ${platform === 'instagram' ? 'Instagram' : 'Twitter/X'}.

**Original Content:**
${baseContent}

**Business Context:**
- Business: ${profile.businessName}
- Industry: ${profile.industry}
- Brand Voice: ${profile.brandVoice || 'professional'}
- Target Audience: ${profile.targetAudience || 'Local customers'}

**Platform-Specific Guidelines:**
${platformGuidelines}

**Requirements:**
- Adapt the content to be platform-appropriate
- Maintain the core message and intent
- Use the brand voice consistently
- Ensure the content is engaging and shareable
- Stay within platform character limits (${PLATFORM_LIMITS[platform].max} characters for ${platform === 'instagram' ? 'Instagram' : 'Twitter/X'})

**Output:**
Return only the adapted content text, nothing else. Do not include any JSON wrapper or metadata.`

  const response = await getOpenAI().chat.completions.create({
    model: 'gpt-4-turbo-preview',
    messages: [
      {
        role: 'system',
        content: `You are an Expert Social Media Strategist specializing in ${platform === 'instagram' ? 'Instagram' : 'Twitter/X'} content creation. You adapt content to be platform-appropriate while maintaining the core message and brand voice. Always return only the adapted content text, no JSON or metadata.`
      },
      {
        role: 'user',
        content: prompt
      }
    ],
    temperature: 0.8,
    max_tokens: platform === 'twitter' ? 500 : 1000
  })

  const adaptedContent = response.choices[0]?.message?.content
  if (!adaptedContent) {
    throw new Error('No adapted content generated by AI')
  }

  return adaptedContent.trim()
}

/**
 * Gets platform-specific guidelines for AI prompts
 */
function getPlatformGuidelines(platform: 'instagram' | 'twitter'): string {
  if (platform === 'instagram') {
    return `- **Instagram**: Visual-first approach, engaging caption with emojis, relevant hashtags (3-10 hashtags), storytelling focus
- Focus on visuals and visual descriptions
- Use line breaks to create visual spacing
- Include a clear call-to-action
- Encourage engagement through questions or prompts`
  } else {
    return `- **Twitter/X**: Concise and punchy (within 280 character limit), engaging hook, strategic hashtags (1-3 hashtags), handles/mentions when relevant
- Lead with the most compelling point
- Use hashtags strategically (not overused)
- Consider thread format if needed (but keep first tweet strong standalone)
- Include a clear call-to-action if space allows`
  }
}

/**
 * Gets optimal posting time suggestion based on platform and business profile
 * For V1, this is a simplified heuristic based on industry and location
 */
export function getOptimalTimingSuggestion(
  platform: SocialPlatform,
  profile: BusinessProfile
): { bestTime: string; reason: string } {
  // Simplified V1 logic - in production, this would use analytics data
  const location = profile.location as { city?: string; timezone?: string } | null
  const timezone = location?.timezone || 'America/New_York'
  
  // Default best times by platform (in user's local timezone)
  // V1.5: Added google_business optimal timing
  const platformOptimalTimes: Record<SocialPlatform, { hour: number; day: string }> = {
    facebook: { hour: 13, day: 'Tuesday' }, // 1 PM Tuesday
    linkedin: { hour: 9, day: 'Wednesday' }, // 9 AM Wednesday
    instagram: { hour: 17, day: 'Thursday' }, // 5 PM Thursday
    twitter: { hour: 12, day: 'Monday' }, // 12 PM Monday
    google_business: { hour: 10, day: 'Friday' } // V1.5: 10 AM Friday for GBP
  }

  const optimal = platformOptimalTimes[platform]
  
  return {
    bestTime: `${optimal.day} at ${optimal.hour}:00`,
    reason: `Based on ${platform} engagement patterns for ${profile.industry} businesses`
  }
}

