/**
 * AI Reply Assistant
 * Generates context-aware reply suggestions for social media messages
 */

import OpenAI from 'openai'
import { BusinessProfile } from '@/libs/chat-core/src/types'
import { SocialMessage, SocialConversation } from './types'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
})

/**
 * Generates a reply suggestion for a social media conversation
 */
export async function getReplySuggestion(
  conversation: SocialConversation,
  messages: SocialMessage[],
  profile: BusinessProfile
): Promise<string> {
  try {
    // Get the last customer message (most recent message from customer)
    const customerMessages = messages.filter(m => m.senderType === 'customer')
    const lastCustomerMessage = customerMessages[customerMessages.length - 1]
    
    if (!lastCustomerMessage) {
      throw new Error('No customer messages found in conversation')
    }

    // Get conversation context (last 5 messages for context)
    const recentMessages = messages.slice(-5).map(m => ({
      sender: m.senderType === 'customer' ? m.senderName : 'You',
      content: m.content
    }))

    const prompt = `
You are an Expert Community Manager. Your job is to write concise, on-brand replies to customer messages on social media.

**Business Context:**
- Business Name: ${profile.businessName}
- Industry: ${profile.industry}
- Location: ${JSON.stringify(profile.location)}
- Brand Voice: ${profile.brandVoice || 'professional and friendly'}
- Services: ${JSON.stringify(profile.services || [])}

**Platform:** ${conversation.platform}
**Conversation Type:** ${conversation.conversationType}

**Recent Conversation Context:**
${recentMessages.map(m => `${m.sender}: ${m.content}`).join('\n')}

**Customer's Latest Message:**
${lastCustomerMessage.content}

**Requirements:**
1. Generate a single, concise reply (under 280 characters for Twitter/X, but appropriate length for the platform)
2. Be helpful, professional, and on-brand
3. Match the tone of the business's brand voice
4. If the message is a question, provide a clear answer
5. If the message is a complaint, be empathetic and offer a solution
6. If the message is a compliment, be gracious and appreciative
7. Keep it conversational and authentic - avoid corporate jargon
8. If relevant, subtly mention services or invite further engagement, but don't be pushy

**Output:**
Return only the reply text, nothing else. No quotes, no explanations, just the reply message.`

    const response = await openai.chat.completions.create({
      model: 'gpt-4-turbo-preview',
      messages: [
        {
          role: 'system',
          content: 'You are an Expert Community Manager who writes concise, on-brand social media replies. Always respond with just the reply text, no explanations or formatting.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.7,
      max_tokens: 300
    })

    const reply = response.choices[0]?.message?.content?.trim()
    if (!reply) {
      throw new Error('No reply generated by AI')
    }

    return reply
  } catch (error: any) {
    console.error('[Reply Assistant] Error generating reply:', error)
    throw new Error(`Failed to generate reply suggestion: ${error.message}`)
  }
}

