/**
 * Image Generation Service
 * Abstracts DALL-E 3 API calls for branded graphic generation
 */

import OpenAI from 'openai'
import { VisualConcept } from './types'

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
})

/**
 * Generates a blog header graphic using DALL-E 3
 * Creates a 16:9 aspect ratio image (1200x675) based on visual concept
 * 
 * @param visualConcept - The visual concept generated by AI (colors, description, text overlay)
 * @param title - The blog post title (for text overlay)
 * @returns Promise resolving to the image URL
 */
export async function generateBrandedGraphic(
  visualConcept: VisualConcept,
  title: string
): Promise<string> {
  try {
    // Build the DALL-E prompt from the visual concept
    const prompt = buildImagePrompt(visualConcept, title)

    const response = await openai.images.generate({
      model: 'dall-e-3',
      prompt: prompt,
      size: '1792x1024', // DALL-E 3 supports this size, closest to 16:9 (we'll crop/resize if needed)
      quality: 'standard',
      n: 1,
      response_format: 'url'
    })

    const imageUrl = response.data?.[0]?.url
    if (!imageUrl) {
      throw new Error('No image URL returned from DALL-E 3')
    }

    return imageUrl
  } catch (error) {
    console.error('Error generating branded graphic:', error)
    throw new Error(`Failed to generate branded graphic: ${error instanceof Error ? error.message : 'Unknown error'}`)
  }
}

/**
 * Builds the DALL-E 3 prompt from visual concept and title
 * Creates a descriptive prompt for a modern blog header graphic
 */
function buildImagePrompt(visualConcept: VisualConcept, title: string): string {
  const colors = visualConcept.colors.length > 0
    ? `using a color palette of ${visualConcept.colors.join(', ')}`
    : 'using a modern, professional color scheme'
  
  const icon = visualConcept.icon
    ? `, featuring ${visualConcept.icon}`
    : ''
  
  const textOverlay = visualConcept.textOverlay || title
  
  // Build the descriptive prompt
  let prompt = `Create a modern blog header graphic ${colors}${icon}. `
  prompt += `The graphic should be a ${visualConcept.description || 'professional illustration'}. `
  prompt += `The image should include the text overlay: "${textOverlay}". `
  prompt += `The design should be clean, modern, and suitable for a professional blog post. `
  prompt += `Use a 16:9 aspect ratio. The style should be modern graphic design or illustration, not a photograph.`

  return prompt
}

/**
 * Generates a fallback image URL if DALL-E fails
 * In production, this might return a placeholder or default image
 */
export function getFallbackImageUrl(): string {
  // For V1, return a placeholder. In production, you might want to:
  // - Use a default branded image
  // - Return null and handle gracefully in the UI
  // - Use a service like Unsplash with a keyword
  return 'https://via.placeholder.com/1200x675?text=Blog+Header'
}

