/**
 * Content Repurposing Engine
 * Generates platform-specific social media assets from blog posts
 */

import OpenAI from 'openai'
import { supabaseAdmin } from '@/lib/supabase'
import { BlogPost, RepurposedAsset } from './types'
import { BusinessProfile } from '../../chat-core/src/types'

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
})

/**
 * Repurposes blog post content into platform-specific social media assets
 * Updates the BlogPost record with repurposedAssets
 * 
 * @param post - The blog post to repurpose
 * @param profile - The business profile for context
 * @param targetPlatforms - The platforms to generate assets for (from content settings)
 * @returns Promise resolving when assets are saved
 */
export async function repurposeContent(
  post: BlogPost,
  profile: BusinessProfile,
  targetPlatforms: Array<'linkedin' | 'facebook' | 'twitter' | 'instagram'> = ['linkedin', 'facebook', 'twitter', 'instagram']
): Promise<void> {
  try {

    // Generate repurposed assets using AI
    const assets = await generateRepurposedAssets(post, profile, targetPlatforms)

    // Update the blog post record with repurposed assets
    const { error } = await supabaseAdmin
      .from('blog_posts')
      .update({
        repurposed_assets: assets
      })
      .eq('id', post.id)

    if (error) {
      throw new Error(`Failed to save repurposed assets: ${error.message}`)
    }
  } catch (error) {
    console.error('Error repurposing content:', error)
    throw new Error(`Failed to repurpose content: ${error instanceof Error ? error.message : 'Unknown error'}`)
  }
}

/**
 * Generates platform-specific social media assets using AI
 */
async function generateRepurposedAssets(
  post: BlogPost,
  profile: BusinessProfile,
  platforms: Array<'linkedin' | 'facebook' | 'twitter' | 'instagram'>
): Promise<RepurposedAsset[]> {
  const prompt = `You are an Expert Social Media Marketing Expert. Your task is to repurpose a blog post into platform-specific social media content.

**Blog Post:**
Title: ${post.title}
Content:
${post.contentMarkdown.substring(0, 3000)}${post.contentMarkdown.length > 3000 ? '...' : ''}

**Business Context:**
- Business: ${profile.businessName}
- Industry: ${profile.industry}
- Brand Voice: ${profile.brandVoice || 'professional'}
- Target Audience: ${profile.targetAudience || 'Local customers'}

**Requirements:**
Generate one social media asset for each of the following platforms: ${platforms.join(', ')}.

Each asset must be:
- Platform-appropriate (follow each platform's best practices)
- Engaging and shareable
- Include a clear call-to-action
- Use the brand voice consistently

**Platform-Specific Guidelines:**
- **LinkedIn**: Professional tone, longer-form content (2-3 paragraphs), thought leadership angle
- **Facebook**: Conversational, community-focused, question or tip format
- **Twitter/X**: Concise (within character limit), engaging hook, hashtags if appropriate
- **Instagram**: Visual-first description, engaging caption with emojis, relevant hashtags

**Output Format:**
Return a JSON object with a "assets" key containing an array of objects:
{
  "assets": [
    {
      "platform": "linkedin",
      "content": "[LinkedIn post content]"
    },
    {
      "platform": "facebook",
      "content": "[Facebook post content]"
    },
    {
      "platform": "twitter",
      "content": "[Twitter/X post content]"
    },
    {
      "platform": "instagram",
      "content": "[Instagram caption]"
    }
  ]
}

Only include assets for the platforms specified: ${platforms.join(', ')}.`

  const response = await openai.chat.completions.create({
    model: 'gpt-4-turbo-preview',
    messages: [
      {
        role: 'system',
        content: 'You are an Expert Social Media Marketing Expert. You repurpose blog content into engaging, platform-specific social media assets. Always return valid JSON that matches the exact structure provided.'
      },
      {
        role: 'user',
        content: prompt
      }
    ],
    temperature: 0.8,
    max_tokens: 2000,
    response_format: { type: 'json_object' }
  })

  const content = response.choices[0]?.message?.content
  if (!content) {
    throw new Error('No content generated by AI')
  }

  // Parse the JSON response
  let parsedData: any
  try {
    parsedData = JSON.parse(content)
  } catch (parseError) {
    throw new Error('Failed to parse AI response as JSON')
  }

  // Extract assets array
  const assets = parsedData.assets || parsedData.repurposedAssets || []

  // Validate and format assets
  const formattedAssets: RepurposedAsset[] = assets
    .filter((asset: any) => 
      asset.platform && 
      platforms.includes(asset.platform) && 
      asset.content
    )
    .map((asset: any) => ({
      platform: asset.platform as RepurposedAsset['platform'],
      content: asset.content.trim(),
      imageUrl: asset.imageUrl || null
    }))

  // Ensure we have assets for all requested platforms
  if (formattedAssets.length < platforms.length) {
    // Generate fallback assets for missing platforms
    const missingPlatforms = platforms.filter(
      p => !formattedAssets.some(a => a.platform === p)
    )
    const fallbackAssets = generateFallbackAssets(post, missingPlatforms)
    formattedAssets.push(...fallbackAssets)
  }

  return formattedAssets.slice(0, platforms.length)
}

/**
 * Generates fallback assets if AI generation fails
 */
function generateFallbackAssets(
  post: BlogPost,
  platforms: Array<'linkedin' | 'facebook' | 'twitter' | 'instagram'>
): RepurposedAsset[] {
  const excerpt = post.contentMarkdown.substring(0, 200).replace(/\n/g, ' ').trim()
  
  return platforms.map(platform => {
    const baseContent = `${post.title}\n\n${excerpt}...`
    
    switch (platform) {
      case 'linkedin':
        return {
          platform: 'linkedin',
          content: `${post.title}\n\n${excerpt}\n\nRead the full article on our blog.`,
          imageUrl: null
        }
      case 'facebook':
        return {
          platform: 'facebook',
          content: `Check out our latest blog post: "${post.title}"\n\n${excerpt}...`,
          imageUrl: null
        }
      case 'twitter':
        return {
          platform: 'twitter',
          content: `${post.title.substring(0, 100)}... ${post.brandedGraphicUrl ? '📸' : ''}`,
          imageUrl: null
        }
      case 'instagram':
        return {
          platform: 'instagram',
          content: `${post.title} 💡\n\n${excerpt}...\n\n#business #blog`,
          imageUrl: null
        }
    }
  })
}

