/**
 * AI Topic & Keyword Suggestion Engine
 * Generates SEO-viable blog post ideas based on business profile
 */

import OpenAI from 'openai'
import { BusinessProfile } from '../../chat-core/src/types'
import { TopicKeywordSuggestion } from './types'

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
})

/**
 * Generates SEO-focused blog post topic and keyword suggestions
 * Returns 5 topic-keyword pairs optimized for local SEO
 * 
 * @param profile - Business profile containing industry, location, services, and target audience
 * @returns Promise resolving to array of 5 topic-keyword pairs
 */
export async function getTopicAndKeywordSuggestions(
  profile: BusinessProfile
): Promise<TopicKeywordSuggestion[]> {
  try {
    // Build context from business profile
    const locationString = profile.location
      ? `${profile.location.city}, ${profile.location.state}`
      : 'your area'
    
    const servicesList = profile.services
      ?.map(s => `- ${s.name}: ${s.description}`)
      .join('\n') || 'General services'
    
    const prompt = `You are an Expert SEO/Content Strategist specializing in local business content marketing.

Your task is to generate 5 SEO-viable blog post topics with associated keywords for the following business:

**Business Information:**
- Industry: ${profile.industry}
- Location: ${locationString}
- Services:
${servicesList}
- Target Audience: ${profile.targetAudience || 'Local customers'}

**Requirements:**
1. Generate exactly 5 topic-keyword pairs
2. Topics must be formatted as ready-to-use blog post titles (no need for refinement)
3. Prioritize question-based titles and "how-to" guides that directly answer user intent
4. Examples of good formats:
   - "How to [action relevant to the business]"
   - "Why is My [common problem]? A Quick Guide"
   - "[Number] Signs You Need to [service-related action]"
   - "[Number] Tips for [audience] in [location]"
5. Keywords must naturally incorporate:
   - The business service/industry
   - Location (city/state) where relevant
   - Local SEO intent (e.g., "emergency plumber san jose")
6. Each keyword should be a simple string (e.g., "local plumber san francisco", "water heater repair tips")
7. Topics should be relevant to the business's services and valuable to their target audience
8. Make topics specific and actionable - avoid generic or overly broad topics

**Output Format:**
Return a JSON object with a "suggestions" key containing an array of exactly 5 objects, each with "topic" and "keyword" fields:
{
  "suggestions": [
    {
      "topic": "How to Tell if Your Water Heater is Failing",
      "keyword": "water heater failure signs"
    },
    {
      "topic": "Emergency Plumbing Services in [City]: What to Expect",
      "keyword": "emergency plumber [city]"
    },
    ...
  ]
}

Replace [City] with the actual city name from the business location.`

    const response = await openai.chat.completions.create({
      model: 'gpt-4-turbo-preview',
      messages: [
        {
          role: 'system',
          content: 'You are an Expert SEO/Content Strategist. You generate SEO-optimized blog post topics and keywords for local businesses. Always return valid JSON arrays with exactly the requested number of items.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.8, // Higher creativity for diverse suggestions
      max_tokens: 1500,
      response_format: { type: 'json_object' }
    })

    const content = response.choices[0]?.message?.content
    if (!content) {
      throw new Error('No content generated by AI')
    }

    // Parse the JSON response
    let parsedData: any
    try {
      parsedData = JSON.parse(content)
    } catch (parseError) {
      // If parsing fails, try to extract JSON from the response
      const jsonMatch = content.match(/\[[\s\S]*\]/)
      if (jsonMatch) {
        parsedData = JSON.parse(jsonMatch[0])
      } else {
        throw new Error('Failed to parse AI response as JSON')
      }
    }

    // Extract the suggestions array
    // The AI should return { suggestions: [...] } but we handle both formats
    const suggestions = Array.isArray(parsedData) 
      ? parsedData 
      : parsedData.suggestions || parsedData.topics || parsedData.results || []

    // Validate and format the suggestions
    const formattedSuggestions: TopicKeywordSuggestion[] = suggestions
      .slice(0, 5) // Ensure we only return 5
      .map((item: any) => {
        // Handle both { topic, keyword } and { title, keyword } formats
        const topic = item.topic || item.title || ''
        const keyword = item.keyword || item.keyphrase || ''
        
        // Replace [City] placeholder with actual city name
        const locationCity = profile.location?.city || ''
        const finalTopic = topic.replace(/\[City\]/g, locationCity)
        const finalKeyword = keyword
          .replace(/\[city\]/g, locationCity.toLowerCase())
          .replace(/\[City\]/g, locationCity)

        return {
          topic: finalTopic.trim(),
          keyword: finalKeyword.trim()
        }
      })
      .filter((item: TopicKeywordSuggestion) => 
        item.topic.length > 0 && item.keyword.length > 0
      )

    // Ensure we have exactly 5 suggestions
    if (formattedSuggestions.length < 5) {
      // Fallback: generate simple suggestions if AI didn't return enough
      const fallbackSuggestions = generateFallbackSuggestions(profile, formattedSuggestions.length)
      formattedSuggestions.push(...fallbackSuggestions.slice(0, 5 - formattedSuggestions.length))
    }

    return formattedSuggestions.slice(0, 5)
  } catch (error) {
    console.error('Error generating topic suggestions:', error)
    
    // Fallback to simple suggestions if AI call fails
    return generateFallbackSuggestions(profile, 5)
  }
}

/**
 * Generates fallback topic-keyword suggestions when AI call fails
 * Creates simple, relevant suggestions based on business profile
 */
function generateFallbackSuggestions(
  profile: BusinessProfile,
  count: number
): TopicKeywordSuggestion[] {
  const location = profile.location
    ? `${profile.location.city}, ${profile.location.state}`
    : ''
  
  const industry = profile.industry || 'business'
  const services = profile.services || []
  const firstService = services[0]?.name || industry

  const fallbackTemplates = [
    {
      topic: `How to Choose the Right ${firstService} Service in ${location}`,
      keyword: `${firstService.toLowerCase()} ${location ? location.split(',')[0].toLowerCase() : ''}`
    },
    {
      topic: `Top 5 Benefits of Professional ${firstService} Services`,
      keyword: `professional ${firstService.toLowerCase()} benefits`
    },
    {
      topic: `Common ${firstService} Problems and How to Fix Them`,
      keyword: `${firstService.toLowerCase()} problems solutions`
    },
    {
      topic: `When to Call a ${firstService} Professional`,
      keyword: `when to call ${firstService.toLowerCase()} professional`
    },
    {
      topic: `${firstService} Tips for ${profile.targetAudience || 'Homeowners'}`,
      keyword: `${firstService.toLowerCase()} tips ${location ? location.split(',')[0].toLowerCase() : ''}`
    }
  ]

  return fallbackTemplates.slice(0, count).map(item => ({
    topic: item.topic,
    keyword: item.keyword.trim()
  }))
}

