/**
 * Content Engine Core Data Structures (Module 3)
 * AI Content Autopilot - Full content marketing strategy
 */

/**
 * Repurposed asset for social media platforms
 * Generated from blog post content for platform-specific distribution
 */
export interface RepurposedAsset {
  platform: 'linkedin' | 'facebook' | 'twitter' | 'instagram'
  content: string
  imageUrl?: string | null
}

/**
 * Blog post status workflow
 * Maps to the approval and publishing workflow
 */
export type BlogPostStatus = 
  | 'draft' 
  | 'scheduled' 
  | 'pending_approval' 
  | 'approved' 
  | 'changes_requested' 
  | 'published'

/**
 * SEO metadata for blog posts
 */
export interface SeoMetadata {
  metaTitle: string
  metaDescription: string
  focusKeyword: string | null
}

/**
 * Blog post structure
 * Represents a complete blog post with SEO, visuals, and repurposed assets
 */
export interface BlogPost {
  id: string
  userId: string
  title: string
  slug: string
  contentMarkdown: string
  seoMetadata: SeoMetadata
  focusKeyword: string | null
  brandedGraphicUrl: string | null
  repurposedAssets: RepurposedAsset[] | null
  status: BlogPostStatus
  approvalToken: string | null
  scheduledAt: Date | null
  publishedAt: Date | null
  createdAt: Date
  updatedAt: Date
}

/**
 * Target platforms for content distribution
 */
export type TargetPlatform = 'linkedin' | 'facebook' | 'twitter' | 'instagram'

/**
 * Publishing frequency options
 */
export type PublishingFrequency = 
  | 'daily' 
  | 'weekly' 
  | 'biweekly' 
  | 'monthly'

/**
 * Content settings per user
 * Controls the content autopilot behavior and strategy
 */
export interface ContentSettings {
  userId: string
  primaryBusinessGoalCta: string | null
  frequency: PublishingFrequency
  targetPlatforms: TargetPlatform[]
  isEnabled: boolean
  createdAt: Date
  updatedAt: Date
}

/**
 * Topic and keyword suggestion
 * Generated by AI based on business profile and SEO strategy
 */
export interface TopicKeywordSuggestion {
  topic: string
  keyword: string
}

/**
 * Draft generation input
 */
export interface DraftGenerationInput {
  topic: string
  keyword: string
  profile: any // BusinessProfile from chat-core
  settings: ContentSettings
}

/**
 * Visual concept for branded graphic generation
 * Generated by AI to guide image creation
 */
export interface VisualConcept {
  colors: string[]
  icon: string | null
  textOverlay: string | null
  description: string
}

/**
 * Approval notification data
 * Sent to user via email/SMS for content approval
 */
export interface ApprovalNotification {
  postId: string
  approvalToken: string
  preview: {
    title: string
    excerpt: string
    brandedGraphicUrl: string | null
    repurposedAssets: RepurposedAsset[]
  }
}

/**
 * Revision feedback
 * User feedback for content changes
 */
export interface RevisionFeedback {
  postId: string
  feedback: string
  requestedChanges: string[]
}

